backend: 
  name: git-gateway
  branch: main
local_backend:
  url: http://localhost:8081/api/v1
  
media_folder: static/images
public_folder: /images

collections:
  - label: Articles 
    label_singular: Article
    name: articles
    folder: content/articles
    slug: '{{slug}}'
    create: true
    fields: 
      - label: Title
        name: title
        widget: string
      - label: Image
        name: image
        widget: image
      - label: Summary
        name: summary
        widget: string
      - label: Body
        name: body
        widget: markdown
      

